# This file was automatically generated by deploy_gitea.sh for Gitea configuration
# DO NOT EDIT MANUALLY!

gitea_base_url = "http://gitea.mydevlab.local"
initial_repo_name = "my-provisioning-repo"
initial_repo_description = "Repository for initial infrastructure provisioning manifests."
gitea_admin_username = "dev-admin"
gitea_admin_password = "SuperSecurePassword!"
initial_argocd_repo = "https://github.com/Xelef2000/kubernetes-lab-argocd-configs.git"
