# config.yaml

tf-config:
  binary_path: tofu

kubernetes:
  kubeconfig: ~/.kube/config
  kubecontext: minikube

gitea-deployment:
  gitea_namespace: gitea-dev
  gitea_release_name: my-gitea-instance
  gitea_admin_username: dev-admin
  gitea_admin_password: "SuperSecurePassword!" 
  gitea_admin_email: dev-admin@example.com
  gitea_url: gitea.mydevlab.local

gitea-config:
  initial_repo_name: my-provisioning-repo
  initial_repo_description: "Repository for initial infrastructure provisioning manifests."
  initial_argocd_repo: "https://github.com/Xelef2000/kubernetes-lab-argocd-configs.git"


argocd-deployment:
  argocd_url: argocd.mydevlab.local
  argocd_namespace: infra-argocd
  argocd_release_name: argocd