
tf-config:
  binary_path: tofu

kubernetes:
  kubeconfig: ~/.kube/config
  kubecontext: minikube

pygitserver-deployment:
  git_namespace: git-server-dev
  git_release_name: my-git-instance
  git_url: git.mydevlab.local
  ingress_class_name: "nginx"
  
  repos:
    - name: "my-first-repo"
      init_from: "" # Creates an empty repository
    - name: "argocd-configs"
      init_from: "https://github.com/Xelef2000/kubernetes-lab-argocd-configs.git"

argocd-deployment:
  argocd_url: argocd.mydevlab.local
  argocd_namespace: infra-argocd
  argocd_release_name: argocd