# This file was automatically generated by deploy_gitea.sh for Gitea deployment
# DO NOT EDIT MANUALLY!

gitea_namespace = "gitea-dev"

gitea_release_name = "my-gitea-instance"

gitea_admin_username = "dev-admin"

gitea_admin_password = "SuperSecurePassword!"

gitea_admin_email = "dev-admin@example.com"

gitea_url = "gitea.mydevlab.local"

kubeconfig = "~/.kube/config"

kubecontext = "minikube"
