# This file was automatically generated by deploy_argocd.sh for Argo CD deployment
# DO NOT EDIT MANUALLY!

argocd_url = "argocd.mydevlab.local"

argocd_namespace = "infra-argocd"

argocd_release_name = "argocd"

kubeconfig = "~/.kube/config"

kubecontext = "minikube"
