# This file was automatically generated by the deployment script
# DO NOT EDIT MANUALLY!

git_namespace = "git-server-dev"

git_release_name = "my-git-instance"

git_url = "git.mydevlab.local"

ingress_class_name = "nginx"

kubeconfig = "~/.kube/config"

kubecontext = "minikube"

repos = [
  {
    "name": "my-first-repo",
    "init_from": ""
  },
  {
    "name": "argocd-configs",
    "init_from": "https://github.com/Xelef2000/kubernetes-lab-argocd-configs.git"
  }
]
